#
# Module manifest for module 'MakeFS'
# Generated by: dskeller
# Generated on: 08.10.2022
#

@{

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # ID used to uniquely identify this module
    GUID              = '98c2d029-938a-4d76-a0ab-83a840fce59e'

    # Author of this module
    Author            = 'dskeller'

    # Copyright statement for this module
    Copyright         = '(c)2022 dskeller. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Collection of functions for server migration'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    #NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = *

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = *

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = 'MakeFS'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/dskeller/_makeFS'
        } # End of PSData hashtable
    } # End of PrivateData hashtable
}

