#
# Module manifest for module 'Write-Log'
# Generated by: dskeller
# Generated on: 08.10.2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule             = 'Write-Log.psm1'

    # Version number of this module.
    ModuleVersion          = '1.0.0'

    #Supported PSEditions
    CompatiblePSEditions   = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                   = '866fb9e3-0975-4abe-a509-40f357c3903e'

    # Author of this module
    Author                 = 'dskeller'

    # Copyright statement for this module
    Copyright              = '2022 by dskeller'

    # Description of the functionality provided by this module
    Description            = 'Module for helper function to write log to stdout and log file.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion      = '5.0'

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '4.7.2'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    ClrVersion             = '4.0'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport      = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport        = '*'

    # Variables to export from this module
    VariablesToExport      = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport        = '*'

    # List of all modules packaged with this module
    ModuleList             = @('Write-Log')

    # List of all files packaged with this module
    FileList               = @('Write-Log.psm1', 'Write-Log.psd1')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData            = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = 'MakeFS'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/dskeller/_makeFS'

            # ReleaseNotes of this module
            # ReleaseNotes = ''
        }
    }
}

